---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: https://msc-bit@github.com/msc-bit/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: mscbit/podinfo
      tag: dev-vutsyvuc
    replicaCount: 1
    hpa:
      enabled: false
