---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.4
spec:
  releaseName: podinfo-prod
  chart:
    git: https://msc-bit:vZ1H8dad9AKUzkaM30CK@github.com/msc-bit/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: mscbit/podinfo
      tag: 0.4.12
    replicaCount: 3
